# Generated by Django 3.2.7 on 2021-11-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
